### ISSUE TITLE
no response after start Indexing

### ISSUE THREAD

**Issue by Shobit51** [m4mallu/clonebot#125]
Hi, Bot deployed successfully on Heroku. Source & Target set. Then it starts indexing but nothing happens afterwards. Am I doing something wrong?

**Comment by prono69** [comment]
Same happening here. Deployed on VPS. But same thing. Please look into this matter

**Comment by m4mallu** [comment]
These kinds of issues are basically associated with DC speed, File availability, file limitations, etc. Nothing can be done in some of these cases.
