### ISSUE TITLE
DONT USE THIS REPOSITORY

### ISSUE THREAD

**Issue by prono69** [m4mallu/clonebot#128]
Nothing happening after Indexing start . Wasted alot of my time , but still no fix .

Please don't use this repository as IT WILL NOT WORK

**Comment by m4mallu** [comment]
Issue due to the updated framework. Use older versions of the framework, pyrogram. I just wanted to let you know that it'll work. If you can push, I'll accept it. Because once it worked, the repository had 266 stars and 721 forks.

**Comment by prono69** [comment]
> Issue due to the updated framework. Use older versions of the framework, pyrogram. I just wanted to let you know that it'll work. If you can push, I'll accept it. Because once it worked, the repository had 266 stars and 721 forks.

Which pyrogram version you recommend to use ? Cause pyrogram v1 is not gonna work because of string session 
And sorry if I am being rude.

**Comment by m4mallu** [comment]
I don't remember the version number exactly (version 2, sure). My lap got wiped off everything.

**Comment by prono69** [comment]
I tried sir but still it's not working 😭 . Can you please kindly look into this matter please 🥺
I really need it

**Comment by m4mallu** [comment]
I'm closing this issue as it misleads the users of this repo. !

**Comment by prono69** [comment]
Ok but at least try which version works . Whatever i do, it's getting stuck at indexing part . No error in logs too
