### ISSUE TITLE
401 USER_DEACTIVATED - Account banned

### ISSUE THREAD

**Issue by chuti0800** [m4mallu/clonebot#139]
I was using a test account, so no problem.

I loaded the source with no problem, then had lots of trouble while trying to load up the target, tried with channel id and chat id, both my user and the bot were admin, but the I got an error mentioning something about me not being a user of the target channel (which I was). 

Then I tried using a user (@) as the target, and all of a sudden in the terminal, this shows up:
[07-Aug-24 11:47:57 - ERROR] - pyrogram.dispatcher - Telegram says: [401 USER_DEACTIVATED] - The user has been deleted/deactivated (caused 
by "messages.DeleteMessages")

So not only I got banned (and I dont know specifically why), but the clone process didnt work. So what should I do to avoid this ban, why did this even happen, and what should I do next time while setting up the target id? 

Thanks in advance.

**Comment by m4mallu** [comment]
Everything is specified in the documentation. So, this can't be an issue anymore.
