### ISSUE TITLE
what sessions?

### ISSUE THREAD

**Issue by ghost** [m4mallu/clonebot#14]
I use telethon string got error - struct.error: unpack requires a buffer of 263 bytes
I use pyrogram string - cant access channel

**Comment by m4mallu** [comment]
**_Your issue is not related to the repo_**. 
Make the session string from any **pyrogram string session maker** and opt for user bot (don't use bot API to generate)
For any further information, read the [Documentation](https://telegra.ph/Clonebot-UI-Help-05-30)
