### ISSUE TITLE
add minimum_length add_minimum size block certain extensions

### ISSUE THREAD

**Issue by sunilroyy007** [m4mallu/clonebot#25]
hey can you add minimum length option and minimum size and block extension 

minimum length - some videos have 2 to 5 minutes duration. i need only above 20 minutes video so this feature will be useful
size - some videos have 2 to 5 minutes duration but have 1GB file size i dont want to transfer them
no extension or block certain extensions - some videos have no extension i dont want those or some videos have .mkv and .mp4 extensions i want to have an option to block which i dont want

1 and 2 are much needed features and verry useful

**Comment by m4mallu** [comment]
These types of sorting is cannot be considered as a global demand. So, the requested feature cannot be included in this master branch.
