### ISSUE TITLE
Caption which is a great feature that will save much time

### ISSUE THREAD

**Issue by mujuaj** [m4mallu/clonebot#32]
Clone bot
I am using it always for forwarding files
The caption feature is also awesome
/setcaption <b>{filename}</b>
▱▰▱▰▱▰▱▰▱▰▱▰
<b>Size: <i>{filesize}</b>

𝗠𝗼𝗿𝗲 𝗠𝗼𝘃𝗶𝗲𝘀
➖@ownerchannel➖
𝗠𝗮𝗶𝗻 𝗰𝗵𝗮𝗻𝗻𝗲𝗹
➖@ownerchannel2➖
Is there any way to add custom caption like this....
It's very useful.....
Please bro
Then i could save hours editing captions....
☺️

**Comment by m4mallu** [comment]
will be considered in the future update.

**Comment by m4mallu** [comment]
The feature requested was committed in the [update](https://github.com/m4mallu/clonebot/commit/51291422822b989752037bee7afd5bd3b61b94ca)
Thanks for the feedback !
