### ISSUE TITLE
Cannot deploy on Heroku . says source code violates salesforce ToS, any way to bypass?

### ISSUE THREAD

**Issue by Runner-boy** [m4mallu/clonebot#34]
Cannot deploy on Heroku . says source code violates salesforce ToS, any way to bypass?

**Comment by m4mallu** [comment]
1. Fork the repo
2. Change App.json **Repository** parameter URL to your fork URL.
3. Change the **deploy button** URL to your fork URL.
4.  Deploy to Heroku **from your fork**.
