### ISSUE TITLE
Option to forword text messages as well.

### ISSUE THREAD

**Issue by ScriptBuddy16** [m4mallu/clonebot#36]
First of all this is very nice bot... A bot I always was looking for... Thanks for building it and I would really appreciate if you can add option to forword text messages as well

**Comment by m4mallu** [comment]
May be considered in the next update..!

**Comment by ScriptBuddy16** [comment]
Thanks for reply bro, will be waiting.!

**Comment by CodeOfDestruction** [comment]
pls update . Thanks

**Comment by stargazer1255** [comment]
**Please add a feature to support text cloning also in clonebot, if it's possible ?**
_Thnkeww_

**Comment by m4mallu** [comment]
The feature requested is updated and [pushed](https://github.com/m4mallu/clonebot/commit/51291422822b989752037bee7afd5bd3b61b94ca).
Thanks for the feedback !
