### ISSUE TITLE
Sir please add support to deploy to railway because the app doesn't restart every 24 hrs

### ISSUE THREAD

**Issue by HithaishiDesai** [m4mallu/clonebot#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akyorer** [comment]
hello dear friend, l am working to deploy to heroku (4 days) and deployed but at final bot doesnt send me any messages, Can you help me please ? l can give my telegram adress

**Comment by m4mallu** [comment]
https://github.com/m4mallu/clonebot/issues/61#issuecomment-1189805197
