### ISSUE TITLE
Error and unable to work

### ISSUE THREAD

**Issue by KelvinCrag** [m4mallu/clonebot#47]
It's not working. Here's logs: https://spaceb.in/mSvbXQCg
![Screenshot_20220523-143410](https://user-images.githubusercontent.com/64832927/169831201-0f9938c2-ffe9-4f55-99c1-06589011f904.png)

**Comment by m4mallu** [comment]
It's already explained [here](https://t.me/rmprojects/79)

**Comment by KelvinCrag** [comment]
Thanks!
