### ISSUE TITLE
Bot not functioning

### ISSUE THREAD

**Issue by Littletonar** [m4mallu/clonebot#55]
Bot starts after deploying but it is not responding on giving source or target chat info (it is not taking any information). 
![IMG_20220528_120644](https://user-images.githubusercontent.com/105858470/170813702-dd3e9825-baf2-4b13-8de4-5bc6431c689a.jpg)

And after that..
![Screenshot_2022-05-28-12-05-22-243_org telegram plus](https://user-images.githubusercontent.com/105858470/170813764-413d843a-5683-49b1-8b96-2f959577d653.jpg)

And there is continuous warning in logs.
![IMG_20220528_113522](https://user-images.githubusercontent.com/105858470/170812619-8feb2120-383e-4775-9a67-6dea4e1485dc.jpg)

Please help me on this issue.

**Comment by m4mallu** [comment]
This repo is not responsible for any server-side issues.
