### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by FANJANDA** [m4mallu/clonebot#60]
**Describe**
First of all this is very nice bot... A bot I always was looking for... Thanks for building it.
I have a group
Some files are infected
'This message couldn't be displayed on your device because it contains pornographic materials.'
However, if the third-party telegram client removes the reference and forwards it to another chat, the infected media file can be displayed normally
Then I found this robot, but it doesn't seem to work. It only forwards normal chat messages. Infected messages won't be forwarded.

**Comment by m4mallu** [comment]
This is not a repo issue, Telegram is always against violating intellectual property rights and pornographic contents. Even though there are so many methods to override the ban, this repo also won't entertain such things. The only thing you can do is, copy the source and edit what you want. Thanks for experiencing the bot.
