### ISSUE TITLE
#Featurerequest

### ISSUE THREAD

**Issue by HithaishiDesai** [m4mallu/clonebot#61]
Hello Sir First of all Thanks for taking TELEGRAM to next level with your Codes. ❤️🙏🏻

#suggestion
✯ Add Deploy to [Okteto](https://www.okteto.com/) 
✯ Add Deploy to [Railway ](https://railway.app/) 

THANKS 🙏🏻

**Comment by m4mallu** [comment]
These all are optional things and are up to the end user's concern. Now I'm planning to remove the "Heroku" link from this repo as the platform is reporting this repo as a potential repository. ! So, attaching the link of these kinds will be a threat for this repo in the future. Perhaps, forking and editing the code as your own will be convenient in this case. ! 

# Request rejected with reason.

**Comment by HithaishiDesai** [comment]
Ok Sir Thanks 🙏🏻

**Comment by HithaishiDesai** [comment]
Hello Sir, I forked and tried to deploy on okteto but it's successfully deployed but it's not running it's showing error on worker

As you mentioned earlier that you can't add it on your original repository

Atleast please add a guide via telegraph or make a pull request to my fork or tell me through telegram


Please Help me out 


My fork : https://github.com/HithaishiDesai/Clone-Bot

Telegram Username : @Hithaishidesai_605
