### ISSUE TITLE
Usage of bot session when cloning from public chats.

### ISSUE THREAD

**Issue by mhdshan** [m4mallu/clonebot#81]
Hello,
Can You Add Indexing And Forwarding From Public Channel Without Session ( Using Bot ) Please 🙏🙏

**Comment by m4mallu** [comment]
For this feature, bot need to be an `admin in the target chat` with `posting privileges`

**Comment by HithaishiDesai** [comment]
> For this feature, bot need to be an `admin in the target chat` with `posting privileges`

Sir Is this feature already available ?

**Comment by prono69** [comment]
There is other repo for that

**Comment by m4mallu** [comment]
> > For this feature, bot need to be an `admin in the target chat` with `posting privileges`
> 
> Sir Is this feature already available ?

Nop

**Comment by mhdshan** [comment]
It Showing Error 𝙎𝙚𝙨𝙨𝙞𝙤𝙣 𝙪𝙨𝙚𝙧 𝙞𝙨 𝙣𝙤𝙩 𝙞𝙣 𝙩𝙝𝙚 𝙩𝙖𝙧𝙜𝙚𝙩 𝙘𝙝𝙖𝙩 𝙜𝙞𝙫𝙚𝙣. It Showing You Are Not Authorized When Trying To Restart. Cannot Stop Cloning . I Have One More Doubt Did The Bot Automatically Forward After Heroku Restarting Or We Need To Do It Manually

**Comment by mhdshan** [comment]
It Showing You Are Not Authorized When Trying To Restart. Cannot Stop Cloning . I Have One More Doubt Did The Bot Automatically Forward After Heroku Restarting Or We Need To Do It Manually

**Comment by HithaishiDesai** [comment]
> It Showing You Are Not Authorized When Trying To Restart. Cannot Stop Cloning . I Have One More Doubt Did The Bot Automatically Forward After Heroku Restarting Or We Need To Do It Manually

Manually

**Comment by m4mallu** [comment]
> It Showing You Are Not Authorized When Trying To Restart. Cannot Stop Cloning . I Have One More Doubt Did The Bot Automatically Forward After Heroku Restarting Or We Need To Do It Manually

1. The `session user account` can only able to restart the bot. 
2. If you have any problem with cancelling the clone process, it's up to your `server response delay or File's DC lag`
3. Bot `won't restart` the process when a free Heroku dyno restarts at its interval, as the bot was really `designed to be operated on a VPS` instead. You can restart it manually from the `CMID` value (information displayed in the on going process) as the `Fr.Id` of a new process after the server restarts
