### ISSUE TITLE
Bug i guess ?

### ISSUE THREAD

**Issue by prono69** [m4mallu/clonebot#83]
So I have generated pyrogram V2 string session from your repl link but still got this error ![here](https://telegra.ph/file/0d27be98180f1ba001fd6.jpg)
**But when I use old string session it's working fine :(**
**And yes I am using latest code** . **Help please**

**Comment by m4mallu** [comment]
Possible reasons:

1. Old repo with new session string
2. New repo with old session starting

The issue is with your variables.

**Comment by PBhadoo** [comment]
> Possible reasons:
> 
> 1. Old repo with new session string
> 2. New repo with old session starting
> 
> The issue is with your variables.

Now this Repo supports the New Session String? or still have to use old one?

**Comment by prono69** [comment]
This repo supports new Pyro string session.

**Comment by m4mallu** [comment]
> This repo supports new Pyro string session.

This repo is supporting **new session string only** !
